In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

## CVS 파일 읽어오기

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df1 = pd.read_csv("./data/winequality-red.csv", index_col=False,sep=';')
df1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [3]:
df2 = pd.read_csv("./data/winequality-white.csv", index_col=False,sep=';')
df2

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [4]:
df= pd.concat([df1,df2])
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[6497 rows x 12 columns]

In [5]:
#컬럼명
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [6]:
# Outcome 개수 확인
df['quality'].value_counts()

quality
6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: count, dtype: int64

In [7]:
#결측치 확인
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [8]:
# 결측치 제거
df = df.dropna()
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

## ML Classification 전처리

In [9]:
X = df.drop('quality',axis=1)
X.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [10]:
y = df['quality']
y.value_counts()

quality
6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: count, dtype: int64

## ML Classification 수행 및 정확도 평가

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(4872, 11) (4872,)
(1625, 11) (1625,)


In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [13]:
# SVM
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.45415384615384613
[[  0   0   6   3   0   0   0]
 [  0   0   9  48   0   0   0]
 [  0   0  74 444   0   0   0]
 [  0   0  74 664   0   0   0]
 [  0   0  14 245   0   0   0]
 [  0   0   2  41   0   0   0]
 [  0   0   0   1   0   0   0]]


In [14]:
# Logstic Regression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.4793846153846154
[[  0   0   4   5   0   0   0]
 [  0   0  26  31   0   0   0]
 [  0   0 238 279   1   0   0]
 [  0   0 196 540   2   0   0]
 [  0   0  36 222   1   0   0]
 [  0   0   2  41   0   0   0]
 [  0   0   0   1   0   0   0]]


C:\Users\yosim\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
#Neural Network
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(X_train, y_train)

pred_nn = clf_nn.predict(X_test)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.5329230769230769
[[  0   1   5   2   1   0   0]
 [  0   0  39  18   0   0   0]
 [  0   2 296 220   0   0   0]
 [  0   0 174 554  10   0   0]
 [  0   1  15 227  16   0   0]
 [  0   0   2  37   4   0   0]
 [  0   0   0   1   0   0   0]]


In [16]:
#Decision Tree
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.5907692307692308
[[  0   1   4   3   1   0   0]
 [  1  12  21  19   3   1   0]
 [  0  22 323 147  24   2   0]
 [  5  18 147 458  90  17   3]
 [  0   5  16  81 149   8   0]
 [  1   1   0  18   5  18   0]
 [  0   0   0   0   1   0   0]]


In [17]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.6781538461538461
[[  0   0   3   6   0   0   0]
 [  1   8  32  16   0   0   0]
 [  0   0 388 123   7   0   0]
 [  0   1 136 552  49   0   0]
 [  0   0   5 113 140   1   0]
 [  0   0   0  16  13  14   0]
 [  0   0   0   0   1   0   0]]


## ML Classification + PolynomialFeature 적용

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

from sklearn.model_selection import train_test_split


(4872, 11) (4872,)
(1625, 11) (1625,)


In [19]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias=False)
X_train_poly = X_train
poly.fit(X_train_poly)
train_poly = poly.transform(X_train_poly)
print(train_poly.shape)

X_test_poly = X_test
test_poly = poly.transform(X_test_poly)
print(test_poly.shape)

(4872, 77)
(1625, 77)


In [20]:
# SVM
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(train_poly, y_train)

pred_svm = clf_svm.predict(test_poly)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.4510769230769231
[[  0   0   6   3   0   0   0]
 [  0   0  12  45   0   0   0]
 [  0   0  97 421   0   0   0]
 [  0   0 102 636   0   0   0]
 [  0   0  20 239   0   0   0]
 [  0   0   3  40   0   0   0]
 [  0   0   0   1   0   0   0]]


In [21]:
# Logstic Regression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(train_poly, y_train)

pred_lr = clf_lr.predict(test_poly)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.4726153846153846
[[  1   1   4   3   0   0   0]
 [  1   0  20  36   0   0   0]
 [  0   1 163 354   0   0   0]
 [  0   1 133 604   0   0   0]
 [  0   0  22 237   0   0   0]
 [  0   0   2  41   0   0   0]
 [  0   0   0   1   0   0   0]]


In [22]:
#Neural Network
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(train_poly, y_train)

pred_nn = clf_nn.predict(test_poly)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.46276923076923077
[[  0   0   6   1   1   0   1]
 [  0   1  44  11   1   0   0]
 [  0   0 414  94  10   0   0]
 [  0   2 391 320  24   1   0]
 [  0   1  79 162  17   0   0]
 [  0   0  10  32   1   0   0]
 [  0   0   0   1   0   0   0]]


In [23]:
#Decision Tree
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(train_poly, y_train)

pred_dt = clf_dt.predict(test_poly)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.5827692307692308
[[  0   1   6   2   0   0   0]
 [  1  13  21  17   5   0   0]
 [  2  13 338 137  25   2   1]
 [  4  14 159 446 103  10   2]
 [  0   5  14  91 133  14   2]
 [  0   1   3  12  10  17   0]
 [  0   0   0   1   0   0   0]]


In [24]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(train_poly, y_train)
pred = rf_clf.predict(test_poly)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.6732307692307692
[[  0   0   4   5   0   0   0]
 [  1   7  33  16   0   0   0]
 [  0   1 382 129   6   0   0]
 [  0   1 145 549  42   1   0]
 [  0   0   2 114 142   1   0]
 [  0   0   0  16  13  14   0]
 [  0   0   0   1   0   0   0]]


## ML Classification + PolynomialFeature + Standard Scale

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

from sklearn.model_selection import train_test_split


(4872, 11) (4872,)
(1625, 11) (1625,)


In [26]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias=False)
X_train_poly = X_train
poly.fit(X_train_poly)
train_poly = poly.transform(X_train_poly)
print(train_poly.shape)

X_test_poly = X_test
test_poly = poly.transform(X_test_poly)
print(test_poly.shape)

(4872, 77)
(1625, 77)


In [27]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_poly)
train_scaled = ss.transform(train_poly)
test_scaled = ss.transform(test_poly)

train_scaled = pd.DataFrame(train_scaled)
test_scaled = pd.DataFrame(test_scaled)

In [28]:
# SVM
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(train_scaled, y_train)

pred_svm = clf_svm.predict(test_scaled)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.564923076923077
[[  0   0   5   4   0   0   0]
 [  0   0  40  17   0   0   0]
 [  0   0 344 173   1   0   0]
 [  0   0 191 519  28   0   0]
 [  0   0   5 199  55   0   0]
 [  0   0   0  32  11   0   0]
 [  0   0   0   1   0   0   0]]


In [29]:
# Logstic Regression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(train_scaled, y_train)

pred_lr = clf_lr.predict(test_scaled)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.544
[[  1   0   2   6   0   0   0]
 [  1   2  39  15   0   0   0]
 [  0   3 330 177   7   1   0]
 [  0   3 201 480  54   0   0]
 [  0   0  16 173  70   0   0]
 [  0   0   1  26  15   1   0]
 [  0   0   0   0   1   0   0]]


In [30]:
#Neural Network
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(train_scaled, y_train)

pred_nn = clf_nn.predict(test_scaled)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.5575384615384615
[[  1   0   3   5   0   0   0]
 [  2   6  35  13   1   0   0]
 [  0  11 364 131  12   0   0]
 [  0   6 241 432  56   3   0]
 [  0   1  17 138  98   5   0]
 [  0   0   1  20  17   5   0]
 [  0   0   0   1   0   0   0]]


In [31]:
#Decision Tree
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(train_scaled, y_train)

pred_dt = clf_dt.predict(test_scaled)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.584
[[  0   1   6   2   0   0   0]
 [  1  13  21  17   5   0   0]
 [  2  14 339 136  24   2   1]
 [  4  14 159 447 102  10   2]
 [  0   5  14  91 133  14   2]
 [  0   1   3  12  10  17   0]
 [  0   0   0   1   0   0   0]]


In [32]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(train_scaled, y_train)
pred = rf_clf.predict(test_scaled)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.6738461538461539
[[  0   0   4   5   0   0   0]
 [  1   7  33  16   0   0   0]
 [  0   1 383 128   6   0   0]
 [  0   1 145 549  42   1   0]
 [  0   0   2 114 142   1   0]
 [  0   0   0  16  13  14   0]
 [  0   0   0   1   0   0   0]]


## ML Classification + PolynomialFeature + Min-Max Scale

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

from sklearn.model_selection import train_test_split


(4872, 11) (4872,)
(1625, 11) (1625,)


In [34]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias=False)
X_train_poly = X_train
poly.fit(X_train_poly)
train_poly = poly.transform(X_train_poly)
print(train_poly.shape)

X_test_poly = X_test
test_poly = poly.transform(X_test_poly)
print(test_poly.shape)

(4872, 77)
(1625, 77)


In [35]:
from sklearn.preprocessing import MinMaxScaler

mMscaler = MinMaxScaler()
mMscaler.fit(train_poly)
train_scaled = mMscaler.transform(train_poly)
test_scaled = mMscaler.transform(test_poly)

train_scaled = pd.DataFrame(train_scaled)
test_scaled = pd.DataFrame(test_scaled)

In [36]:
# SVM
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(train_scaled, y_train)

pred_svm = clf_svm.predict(test_scaled)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.5495384615384615
[[  0   0   4   5   0   0   0]
 [  0   0  37  20   0   0   0]
 [  0   0 331 185   2   0   0]
 [  0   0 196 519  23   0   0]
 [  0   0   6 210  43   0   0]
 [  0   0   0  33  10   0   0]
 [  0   0   0   0   1   0   0]]


In [37]:
# Logstic Regression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(train_scaled, y_train)

pred_lr = clf_lr.predict(test_scaled)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.5396923076923077
[[  1   0   4   4   0   0   0]
 [  0   0  39  18   0   0   0]
 [  0   0 322 193   3   0   0]
 [  0   0 205 500  33   0   0]
 [  0   0  17 188  54   0   0]
 [  0   0   0  32  11   0   0]
 [  0   0   0   0   1   0   0]]


In [38]:
#Neural Network
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(train_scaled, y_train)

pred_nn = clf_nn.predict(test_scaled)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.5526153846153846
[[  1   0   3   5   0   0   0]
 [  1   1  41  13   1   0   0]
 [  0   3 371 135   9   0   0]
 [  0   2 237 439  60   0   0]
 [  0   0   6 167  86   0   0]
 [  0   0   1  22  20   0   0]
 [  0   0   0   0   1   0   0]]


In [39]:
#Decision Tree
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(train_scaled, y_train)

pred_dt = clf_dt.predict(test_scaled)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.5833846153846154
[[  0   1   6   2   0   0   0]
 [  1  13  21  17   5   0   0]
 [  2  14 339 136  24   2   1]
 [  4  14 159 446 103  10   2]
 [  0   5  14  91 133  14   2]
 [  0   1   3  12  10  17   0]
 [  0   0   0   1   0   0   0]]


In [40]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(train_scaled, y_train)
pred = rf_clf.predict(test_scaled)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.672
[[  0   0   4   5   0   0   0]
 [  1   7  34  15   0   0   0]
 [  0   1 383 128   6   0   0]
 [  0   1 147 546  43   1   0]
 [  0   0   2 114 142   1   0]
 [  0   0   0  16  13  14   0]
 [  0   0   0   1   0   0   0]]


## ML Classification + PolynomialFeature + Robust Scale

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

from sklearn.model_selection import train_test_split


(4872, 11) (4872,)
(1625, 11) (1625,)


In [42]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias=False)
X_train_poly = X_train
poly.fit(X_train_poly)
train_poly = poly.transform(X_train_poly)
print(train_poly.shape)

X_test_poly = X_test
test_poly = poly.transform(X_test_poly)
print(test_poly.shape)

(4872, 77)
(1625, 77)


In [43]:
from sklearn.preprocessing import RobustScaler

ro = RobustScaler()
ro.fit(train_poly)
train_scaled = ro.transform(train_poly)
test_scaled = ro.transform(test_poly)

train_scaled = pd.DataFrame(train_scaled)
test_scaled = pd.DataFrame(test_scaled)

In [44]:
# SVM
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(train_scaled, y_train)

pred_svm = clf_svm.predict(test_scaled)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.5587692307692308
[[  0   0   4   5   0   0   0]
 [  0   0  39  18   0   0   0]
 [  0   0 337 180   1   0   0]
 [  0   0 191 529  18   0   0]
 [  0   0   6 211  42   0   0]
 [  0   0   0  36   7   0   0]
 [  0   0   0   1   0   0   0]]


In [45]:
# Logstic Regression
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(train_scaled, y_train)

pred_lr = clf_lr.predict(test_scaled)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.5390769230769231
[[  1   0   2   6   0   0   0]
 [  1   2  38  16   0   0   0]
 [  0   2 326 181   8   1   0]
 [  0   3 200 485  49   1   0]
 [  0   0  16 181  62   0   0]
 [  0   0   1  27  15   0   0]
 [  0   0   0   0   1   0   0]]


In [46]:
#Neural Network
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(train_scaled, y_train)

pred_nn = clf_nn.predict(test_scaled)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.5636923076923077
[[  1   0   4   3   1   0   0]
 [  1   4  40  10   2   0   0]
 [  0   6 360 137  12   3   0]
 [  1   3 217 445  69   3   0]
 [  0   0  14 137 101   7   0]
 [  0   0   1  16  21   5   0]
 [  0   0   0   1   0   0   0]]


In [47]:
#Decision Tree
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(train_scaled, y_train)

pred_dt = clf_dt.predict(test_scaled)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.5827692307692308
[[  0   1   6   2   0   0   0]
 [  1  13  20  18   5   0   0]
 [  2  14 338 136  25   2   1]
 [  4  14 159 446 103  10   2]
 [  0   5  14  91 133  14   2]
 [  0   1   3  12  10  17   0]
 [  0   0   0   1   0   0   0]]


In [48]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(train_scaled, y_train)
pred = rf_clf.predict(test_scaled)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.6738461538461539
[[  0   0   4   5   0   0   0]
 [  1   7  33  16   0   0   0]
 [  0   1 383 128   6   0   0]
 [  0   1 145 549  42   1   0]
 [  0   0   3 113 142   1   0]
 [  0   0   0  16  13  14   0]
 [  0   0   0   1   0   0   0]]
